// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyh5XZU9j9muUNL2E2rk59k2D45lMOY4U',
    appId: '1:98602473214:web:a717af4766233a5e2237af',
    messagingSenderId: '98602473214',
    projectId: 'the-owensboro-app',
    authDomain: 'the-owensboro-app.firebaseapp.com',
    storageBucket: 'the-owensboro-app.firebasestorage.app',
    measurementId: 'G-60S5J6CHN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDRAfIws8E1JO3JYL2iCUW3jsbzd469E',
    appId: '1:98602473214:android:54b1ed9addc283112237af',
    messagingSenderId: '98602473214',
    projectId: 'the-owensboro-app',
    storageBucket: 'the-owensboro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yF7sAbECbjm_xIZk4c_4hqVPQShX0yM',
    appId: '1:98602473214:ios:a93762eee10d07162237af',
    messagingSenderId: '98602473214',
    projectId: 'the-owensboro-app',
    storageBucket: 'the-owensboro-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterflowCustomWidget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yF7sAbECbjm_xIZk4c_4hqVPQShX0yM',
    appId: '1:98602473214:ios:a93762eee10d07162237af',
    messagingSenderId: '98602473214',
    projectId: 'the-owensboro-app',
    storageBucket: 'the-owensboro-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterflowCustomWidget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyh5XZU9j9muUNL2E2rk59k2D45lMOY4U',
    appId: '1:98602473214:web:2dbe1d7977e5a3002237af',
    messagingSenderId: '98602473214',
    projectId: 'the-owensboro-app',
    authDomain: 'the-owensboro-app.firebaseapp.com',
    storageBucket: 'the-owensboro-app.firebasestorage.app',
    measurementId: 'G-B02ZKHNFEK',
  );
}
